version: '3'
services:
  ###############################
  # APP SERVICES
  ##############################
  app:
    restart: always
    build:
      context: src/docker
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3000:3000
    networks:
      - sunartha-network
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
  ###############################
  # DTABASE SERVICES
  ##############################
  db:
    restart: always
    build:
      context: src/docker
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - sunartha-network
    volumes:
      - pg:/var/lib/pg/data
###############################
# VOLUME PERSISTENT DATA
##############################
volumes:
  pg:
###############################
# NETWORK GROUP SHARING
##############################
networks:
  sunartha-network:
